# Generated by Django 5.1.1 on 2024-10-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
